# Generated by Django 5.2.6 on 2025-11-11 13:26

import django.db.models.manager
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
                ("data", django.db.models.manager.Manager()),
            ],
        ),
    ]
