"""
Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import environ
from django.urls import reverse_lazy
from icecream import install
from pypugjs.ext.django.compiler import enable_pug_translations

from my_secrets import secrets

enable_pug_translations()
install()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
    SITE_ID=(int, 1),
    EMAIL_BACKEND=(str, "django.core.mail.backends.smtp.EmailBackend"),
    DEFAULT_FROM_EMAIL=(str, "noreply@flaeming-wildhandel.de"),
)
environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("SECRET_KEY", default=getattr(secrets, "SECRET_KEY", ""))
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY must be set via .env or my_secrets")

SITE_ID = env("SITE_ID")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"]) + ["0.0.0.0", "testserver"]
INSTALLED_APPS = [
    # our own stuff
    "sample_app",
    "users",
    "offers",
    "utils",
    # Django
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    # 3rd party apps
    "axes",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "compressor",
    "django_crontab",
    "django_extensions",
    "django_secrets",
    "django_tasks",
    "django_tasks.backends.database",
    "loginas",
    "kronos",
    "post_office",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "axes.backends.AxesBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.account",
            ],
            "loaders": [
                # PyPugJS part:   ##############################
                (
                    "pypugjs.ext.django.Loader",
                    (
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ),
                )
            ],
            "builtins": ["pypugjs.ext.django.templatetags"],
        },
    }
]

AUTH_USER_MODEL = "users.User"
ROOT_URLCONF = "settings.urls"
WSGI_APPLICATION = "settings.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "transaction_mode": "EXCLUSIVE",
            "timeout": 5,  # seconds
            "init_command": """
                    PRAGMA journal_mode=WAL;
                    PRAGMA synchronous=NORMAL;
                    PRAGMA mmap_size = 134217728;
                    PRAGMA auto_vacuum = FULL;
                    PRAGMA journal_size_limit = 27103364;
                    PRAGMA cache_size=2000;
                """,
        },
    }
    # PLEASE, as soon as the project gets a lil more serious => use Postgres!
    # BUT the new WAL mode of SQLite should be good enough for small to medium projects
    #############################################################################################
    #  'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'db_name',
    #     'USER': 'username',
    #     'PASSWORD': secrets.DB_PASSWORD,
    #     'HOST': '127.0.0.1',
    #     'PORT': '5432',
    #     'ATOMIC_REQUESTS': True,  # enables automatic rollback on broken requests
    # }
}
CACHES = {
    "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    "axes_cache": {"BACKEND": "django.core.cache.backends.dummy.DummyCache"},
}
TASKS = {"default": {"BACKEND": "django_tasks.backends.database.DatabaseBackend"}}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]
AXES_LOGIN_FAILURE_LIMIT = 2
AXES_CACHE = "axes_cache"
AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = "de"
TIME_ZONE = "Europe/Berlin"
USE_I18N = True
USE_TZ = True


# static assets & uploads
STATIC_URL = "static/"
STATICFILES_DIRS = [path for path in [BASE_DIR / "assets", BASE_DIR / "static"] if path.exists()]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]
MEDIA_URL = "/media/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"
COMPRESS_PRECOMPILERS = (("text/x-sass", "sass {infile} {outfile}"),)
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True

EMAIL_BACKEND = env("EMAIL_BACKEND")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
LOGIN_REDIRECT_URL = "/angebote/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_URL = "/login/"

# django-allauth configuration
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "first_name*",
    "last_name*",
    "street*",
    "house_number*",
    "postal_code*",
    "city*",
    "password1*",
    "password2*",
]
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Fläming Wildhandel] "
ACCOUNT_RATE_LIMITS = {"login_failed": "5/10m"}
ACCOUNT_FORMS = {"signup": "users.forms.UserSignupForm"}

# sentry_sdk.init(
#     dsn=secrets.SENTRY_DSN,
#
#     integrations=[DjangoIntegration()],
#
#     # Set traces_sample_rate to 1.0 to capture 100%
#     # of transactions for performance monitoring.
#     # We recommend adjusting this value in production,
#     traces_sample_rate=1.0,
#
#     # If you wish to associate users to errors (assuming you are using
#     # django.contrib.auth) you may enable sending PII data.
#     send_default_pii=True,
#
#     # By default the SDK will try to use the SENTRY_RELEASE
#     # environment variable, or infer a git commit
#     # SHA as release, however you may want to set
#     # something more human-readable.
#     # release="myapp@1.0.0",
# )

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

EMAIL_OVERRIDE_ADDRESS = None
EMAIL_FOOTER = ""
EMAIL_BACKEND = "post_office.EmailBackend"

SILENCED_SYSTEM_CHECKS = ["debug_toolbar.W006"]

JAZZMIN_SETTINGS = {
    "site_title": "Fläming Wildhandel Verwaltung",
    "site_header": "Fläming Wildhandel",
    "site_brand": "Fläming Wildhandel",
    "welcome_sign": "Willkommen im Adminbereich",
    "topmenu_links": [
        {"name": "Zur Website", "url": "/", "permissions": ["offers.view_offer"]},
    ],
    "usermenu_links": [
        {"name": "Startseite", "url": "/angebote/"},
    ],
    "show_ui_builder": False,
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar_fixed": True,
    "sidebar_fixed": False,
}


def can_login_as(request, target_user):
    return request.user.is_superuser and not target_user.is_superuser


CAN_LOGIN_AS = can_login_as
LOGINAS_REDIRECT_URL = "/admin/"
LOGINAS_LOGOUT_REDIRECT_URL = reverse_lazy("admin:index")

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "utils.IsOwnerOrSuperAdmin",
    ],
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "utils.NoFormBrowsableAPIRenderer",  # removes the form and thus a lot of unnecessary queries
    ),
}

CRONJOBS = [
    ("0 8 * * *", "django.core.management.call_command", ["send_offer_reminders"]),
]
