# Generated by Django 5.2.6 on 2025-11-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("beschreibung", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("bestell_start", models.DateTimeField(verbose_name="Bestellfenster ab")),
                ("bestell_ende", models.DateTimeField(verbose_name="Bestellfenster bis")),
                ("abhol_von", models.DateField(verbose_name="Abholung ab")),
                ("abhol_bis", models.DateField(verbose_name="Abholung bis")),
                ("limit_gesamt", models.PositiveIntegerField(verbose_name="Verfügbare Menge insgesamt")),
                (
                    "limit_pro_user",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Maximal pro Kunde"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["bestell_start", "titel"],
                "verbose_name": "Angebot",
                "verbose_name_plural": "Angebote",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("menge", models.PositiveIntegerField(verbose_name="Menge")),
                ("zustimmung_verbindlich_at", models.DateTimeField(verbose_name="Verbindlich bestätigt am")),
                ("erstellt_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="offers.offer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["offer", "user__last_name", "user__postal_code"],
                "verbose_name": "Bestellung",
                "verbose_name_plural": "Bestellungen",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("empfaenger", models.EmailField(max_length=254)),
                ("typ", models.CharField(choices=[("verify", "Verifizierung"), ("confirm", "Bestätigung"), ("reminder_pre", "Erinnerung vor Abholung"), ("reminder_start", "Erinnerung Abholbeginn")], max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("zustellstatus", models.CharField(default="gesendet", max_length=50)),
                ("nachricht_id", models.CharField(blank=True, max_length=255)),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="offers.offer",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="offers.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "E-Mail-Protokoll",
                "verbose_name_plural": "E-Mail-Protokolle",
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "typ",
                    models.CharField(
                        choices=[("verbindlichkeit", "Verbindlichkeit"), ("newsletter", "Newsletter"), ("agb", "AGB")],
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("text_version", models.TextField()),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="offers.offer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Einwilligung",
                "verbose_name_plural": "Einwilligungen",
            },
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(fields=("user", "offer"), name="unique_registration_per_offer"),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(check=models.Q(('menge__gte', 1)), name="registration_min_one"),
        ),
    ]
